spring:
  datasource:
    url: jdbc:mysql://localhost:3307/redis?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qkrgmldns3#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379


springdoc:
  swagger-ui:
    path: /docs/swagger